### ISSUE TITLE
Enhance Tasks behavior

### ISSUE THREAD

**Issue by enzom-uy** [dineshkhadka/stratus#2]
Hey! I was looking at reddit before going to sleep and saw your project in [this post](https://www.reddit.com/r/reactjs/comments/ug3lpo/i_want_to_review_your_code/) where I also posted code for feedback. I really like browser customizing so this got my attention :)!

**Issue:** when you create a new task, the circle to the left appears to be a button since when you hover it, it turns the cursor to pointer, but it doesn't do anything. It seems that to actually mark a task as completed you have to click the task itself, but there's no cursor: pointer there. Also, if you click a couple of times and a bit fast, the task text is selected and it feels weird.

Maybe it's intended to be that way, and if so thats completely fine! I just wanted to share what was my first reaction to the UI I saw, and how strange it seemed to me that things I expected to happen based on the UI provided, didn't happen in the end.

If you agree with what I said, i'm willing to make the changes myself if it's okay to you, although if you want to do it too that's fine.

Demo of what I mean: 
![Gif demo](https://i.imgur.com/xfowClk.gif)

**Comment by dineshkhadka** [comment]
Hello enzom-uy,

Thanks for checking out my project. 

I love your suggestions. I'd be more than happy if you want to make this better. Please go ahead and I'll pull the changes.


Cheers

**Comment by enzom-uy** [comment]
Sure! Assign me to this issue and I'll start working on it as soon as possible.
